// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Obiekty.model;

#nullable disable

namespace Obiekty.Migrations
{
    [DbContext(typeof(ObiektyContext))]
    partial class ObiektyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Obiekty.model.Obiekt", b =>
                {
                    b.Property<int>("IdObiekt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdObiekt"), 1L, 1);

                    b.Property<int>("CenaBiletu")
                        .HasColumnType("int")
                        .HasColumnName("Cena_biletu");

                    b.Property<int>("CenaBiletuVip")
                        .HasColumnType("int")
                        .HasColumnName("Cena_biletu_vip");

                    b.Property<int>("IloscMiejsc")
                        .HasColumnType("int")
                        .HasColumnName("Ilosc_miejsc");

                    b.Property<string>("Lokalizacja")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("lokalizacja");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdObiekt")
                        .HasName("PK__obiekt__4DB25A0C40E50CC4");

                    b.ToTable("obiekt");
                });
#pragma warning restore 612, 618
        }
    }
}
